"use client";

import { useState } from "react";
import { ImageUpload } from "@/components/admin/image-upload";
import { ProjectBlocks } from "@/components/project-blocks/project-block-renderer";
import type { ProjectBlock, ProjectImage } from "@/types/project";

const labels: Record<ProjectBlock["type"], string> = {
  text: "Texto", image: "Imagem", gallery: "Galeria", video: "Vídeo", "live-demo": "Projeto ao vivo", "two-view": "Duas visualizações",
};

function emptyImage(): ProjectImage { return { url: "", alt: "", caption: "" }; }
function createBlock(type: ProjectBlock["type"], order: number): ProjectBlock {
  const base = { id: crypto.randomUUID(), order };
  switch (type) {
    case "text": return { ...base, type, title: "", subtitle: "", paragraphs: [""], listItems: [], alignment: "left", width: "normal" };
    case "image": return { ...base, type, image: emptyImage(), layout: "normal" };
    case "gallery": return { ...base, type, title: "", images: [emptyImage()], layout: "grid" };
    case "video": return { ...base, type, title: "", url: "", caption: "", poster: "", autoplay: false };
    case "live-demo": return { ...base, type, title: "", description: "", url: "", embedEnabled: true, openExternalEnabled: true, previewImage: "" };
    case "two-view": return { ...base, type, title: "", description: "", viewA: { ...emptyImage(), label: "Frente" }, viewB: { ...emptyImage(), label: "Verso" } };
  }
}

function ordered(blocks: ProjectBlock[]) { return blocks.map((block, order) => ({ ...block, order })); }
function summary(block: ProjectBlock) {
  if (block.type === "text" || block.type === "gallery" || block.type === "video" || block.type === "live-demo" || block.type === "two-view") return block.title || labels[block.type];
  return block.image.alt || labels[block.type];
}

function ImageFields({ label, image, onChange }: { label: string; image: ProjectImage; onChange: (image: ProjectImage) => void }) {
  return <div className="admin-block-subpanel"><strong>{label}</strong><ImageUpload label="Imagem" value={image.url} onChange={(url) => onChange({ ...image, url })} required /><input aria-label={`Texto alternativo de ${label}`} onChange={(event) => onChange({ ...image, alt: event.target.value })} placeholder="Texto alternativo obrigatório" required value={image.alt} /><input aria-label={`Legenda de ${label}`} onChange={(event) => onChange({ ...image, caption: event.target.value })} placeholder="Legenda opcional" value={image.caption ?? ""} /></div>;
}

export function ProjectBlockEditor({ initialBlocks }: { initialBlocks: ProjectBlock[] }) {
  const [blocks, setBlocks] = useState<ProjectBlock[]>(ordered(initialBlocks));
  const [preview, setPreview] = useState(false);
  function replace(index: number, block: ProjectBlock) { setBlocks((current) => current.map((item, itemIndex) => itemIndex === index ? { ...block, order: index } : item)); }
  function move(index: number, direction: -1 | 1) { setBlocks((current) => { const target = index + direction; if (target < 0 || target >= current.length) return current; const next = [...current]; [next[index], next[target]] = [next[target], next[index]]; return ordered(next); }); }
  function duplicate(index: number) { setBlocks((current) => { const clone = structuredClone(current[index]); clone.id = crypto.randomUUID(); return ordered([...current.slice(0, index + 1), clone, ...current.slice(index + 1)]); }); }
  function remove(index: number) { setBlocks((current) => ordered(current.filter((_, itemIndex) => itemIndex !== index))); }

  return <section className="admin-form-section">
    <div className="admin-form-heading"><div><span>04</span><h2>Conteúdo do projeto</h2></div><p>Adicione, edite e reorganize os blocos do case.</p></div>
    <input name="blocks" type="hidden" value={JSON.stringify(blocks)} readOnly />
    <div className="admin-block-list">
      {blocks.map((block, index) => <article className="admin-block" key={block.id}>
        <div className="admin-block-toolbar"><div><span>{String(index + 1).padStart(2, "0")}</span><strong>{labels[block.type]} — {summary(block)}</strong></div><div><button disabled={index === 0} onClick={() => move(index, -1)} type="button" aria-label="Mover bloco para cima">↑</button><button disabled={index === blocks.length - 1} onClick={() => move(index, 1)} type="button" aria-label="Mover bloco para baixo">↓</button><button onClick={() => duplicate(index)} type="button">Duplicar</button><button onClick={() => remove(index)} type="button">Excluir</button></div></div>
        {block.type === "text" ? <div className="admin-form-grid"><div className="admin-field"><label>Título</label><input onChange={(event) => replace(index, { ...block, title: event.target.value })} value={block.title ?? ""} /></div><div className="admin-field"><label>Subtítulo</label><input onChange={(event) => replace(index, { ...block, subtitle: event.target.value })} value={block.subtitle ?? ""} /></div><div className="admin-field admin-field-wide"><label>Texto</label><textarea onChange={(event) => replace(index, { ...block, paragraphs: event.target.value.split(/\n\n+/) })} placeholder="Separe parágrafos com uma linha em branco" rows={7} value={block.paragraphs.join("\n\n")} /></div><div className="admin-field"><label>Alinhamento</label><select onChange={(event) => replace(index, { ...block, alignment: event.target.value as "left" | "center" })} value={block.alignment}><option value="left">Esquerda</option><option value="center">Centralizado</option></select></div><div className="admin-field"><label>Largura</label><select onChange={(event) => replace(index, { ...block, width: event.target.value as "narrow" | "normal" | "wide" })} value={block.width}><option value="narrow">Estreita</option><option value="normal">Normal</option><option value="wide">Ampla</option></select></div><div className="admin-field admin-field-wide"><label>Lista simples</label><textarea onChange={(event) => replace(index, { ...block, listItems: event.target.value.split(/\r?\n/).filter(Boolean) })} placeholder="Um item por linha (opcional)" rows={4} value={(block.listItems ?? []).join("\n")} /></div></div> : null}
        {block.type === "image" ? <><ImageFields label="Imagem" image={block.image} onChange={(image) => replace(index, { ...block, image })} /><div className="admin-field"><label>Layout</label><select onChange={(event) => replace(index, { ...block, layout: event.target.value as "normal" | "wide" | "full" })} value={block.layout}><option value="normal">Normal</option><option value="wide">Amplo</option><option value="full">Tela inteira</option></select></div></> : null}
        {block.type === "gallery" ? <><div className="admin-form-grid"><div className="admin-field"><label>Título</label><input onChange={(event) => replace(index, { ...block, title: event.target.value })} value={block.title ?? ""} /></div><div className="admin-field"><label>Layout</label><select onChange={(event) => replace(index, { ...block, layout: event.target.value as "grid" | "carousel" | "editorial" })} value={block.layout}><option value="grid">Grade</option><option value="carousel">Carrossel</option><option value="editorial">Editorial</option></select></div></div>{block.images.map((image, imageIndex) => <div className="admin-gallery-item" key={`${block.id}-${imageIndex}`}><ImageFields label={`Imagem ${imageIndex + 1}`} image={image} onChange={(nextImage) => replace(index, { ...block, images: block.images.map((item, itemIndex) => itemIndex === imageIndex ? nextImage : item) })} /><div><button disabled={imageIndex === 0} onClick={() => { const images = [...block.images]; [images[imageIndex - 1], images[imageIndex]] = [images[imageIndex], images[imageIndex - 1]]; replace(index, { ...block, images }); }} type="button">↑</button><button disabled={imageIndex === block.images.length - 1} onClick={() => { const images = [...block.images]; [images[imageIndex + 1], images[imageIndex]] = [images[imageIndex], images[imageIndex + 1]]; replace(index, { ...block, images }); }} type="button">↓</button><button disabled={block.images.length === 1} onClick={() => replace(index, { ...block, images: block.images.filter((_, itemIndex) => itemIndex !== imageIndex) })} type="button">Remover</button></div></div>)}<button className="admin-secondary-button" onClick={() => replace(index, { ...block, images: [...block.images, emptyImage()] })} type="button">+ Adicionar imagem</button></> : null}
        {block.type === "video" ? <div className="admin-form-grid"><div className="admin-field"><label>Título</label><input onChange={(event) => replace(index, { ...block, title: event.target.value })} value={block.title ?? ""} /></div><div className="admin-field"><label>URL do vídeo</label><input onChange={(event) => replace(index, { ...block, url: event.target.value })} required type="url" value={block.url} /></div><div className="admin-field"><label>Legenda</label><input onChange={(event) => replace(index, { ...block, caption: event.target.value })} value={block.caption ?? ""} /></div><ImageUpload label="Poster" value={block.poster ?? ""} onChange={(poster) => replace(index, { ...block, poster })} /><label className="admin-check"><input checked={block.autoplay} onChange={(event) => replace(index, { ...block, autoplay: event.target.checked })} type="checkbox" /> Reprodução automática sem áudio</label></div> : null}
        {block.type === "live-demo" ? <div className="admin-form-grid"><div className="admin-field"><label>Título</label><input onChange={(event) => replace(index, { ...block, title: event.target.value })} required value={block.title} /></div><div className="admin-field"><label>URL</label><input onChange={(event) => replace(index, { ...block, url: event.target.value })} required type="url" value={block.url} /></div><div className="admin-field admin-field-wide"><label>Descrição</label><textarea onChange={(event) => replace(index, { ...block, description: event.target.value })} rows={3} value={block.description ?? ""} /></div><ImageUpload label="Imagem de prévia" value={block.previewImage ?? ""} onChange={(previewImage) => replace(index, { ...block, previewImage })} /><div className="admin-toggle-stack"><label><input checked={block.embedEnabled} onChange={(event) => replace(index, { ...block, embedEnabled: event.target.checked })} type="checkbox" /> Mostrar preview incorporado</label><label><input checked={block.openExternalEnabled} onChange={(event) => replace(index, { ...block, openExternalEnabled: event.target.checked })} type="checkbox" /> Mostrar link externo</label></div></div> : null}
        {block.type === "two-view" ? <><div className="admin-form-grid"><div className="admin-field"><label>Título</label><input onChange={(event) => replace(index, { ...block, title: event.target.value })} required value={block.title} /></div><div className="admin-field"><label>Descrição</label><input onChange={(event) => replace(index, { ...block, description: event.target.value })} value={block.description ?? ""} /></div></div><div className="admin-two-view-editor"><ImageFields label={block.viewA.label || "Visualização A"} image={block.viewA} onChange={(viewA) => replace(index, { ...block, viewA: { ...viewA, label: block.viewA.label } })} /><div className="admin-field"><label>Rótulo A</label><input onChange={(event) => replace(index, { ...block, viewA: { ...block.viewA, label: event.target.value } })} required value={block.viewA.label} /></div><ImageFields label={block.viewB.label || "Visualização B"} image={block.viewB} onChange={(viewB) => replace(index, { ...block, viewB: { ...viewB, label: block.viewB.label } })} /><div className="admin-field"><label>Rótulo B</label><input onChange={(event) => replace(index, { ...block, viewB: { ...block.viewB, label: event.target.value } })} required value={block.viewB.label} /></div></div></> : null}
      </article>)}
      {!blocks.length ? <div className="admin-empty-state">Nenhum bloco ainda. O conteúdo legado continuará visível até você adicionar o primeiro.</div> : null}
    </div>
    <div className="admin-add-block"><span>Adicionar bloco</span>{(Object.keys(labels) as ProjectBlock["type"][]).map((type) => <button key={type} onClick={() => setBlocks((current) => [...current, createBlock(type, current.length)])} type="button">{labels[type]}</button>)}</div>
    {blocks.length ? <><button className="admin-preview-toggle" onClick={() => setPreview((current) => !current)} type="button">{preview ? "Fechar prévia" : "Pré-visualizar conteúdo"}</button>{preview ? <div className="admin-content-preview"><ProjectBlocks blocks={blocks} /></div> : null}</> : null}
  </section>;
}
